global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-dev'
    static_configs:
      - targets: ['api-dev:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres-dev'
    static_configs:
      - targets: ['postgres-dev:5432']

  - job_name: 'redis-dev'
    static_configs:
      - targets: ['redis-dev:6379']
